### ISSUE TITLE
Cannot clone repository - bad submodule address

### ISSUE THREAD

**Issue by jhaws1982** [commtech/fscc-linux#1]
I was trying to clone the repository in order to be able to use it and it failed to clone with a submodule issue on utils/wireshark.

The problem is that the path was added as git@github.com:commtech/wfscc.git, however that isn't publically available to clone from.  If I edit the .git/config file to change that to git://github.com/commtech/wfscc.git, the "git submodule update" command will work and the clone succeeds.

Can this be fixed?
Thanks!

**Comment by lunruh** [comment]
Fixed, thanks for letting us know!
